name: Code tests

on: [pull_request]

jobs:
  code-tests:
    name: Run code tests
    runs-on: "ubuntu-18.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/marketplace/actions/setup-conda
      - name: Setup anaconda
        uses: s-weigand/setup-conda@v1
        with:
          conda-channels: "conda-forge"

      # Build cache of environment
      - name: Cache conda environment
        id: cache-environment
        uses: actions/cache@v2
        # Conda environment build step depends on two files,
        # so we ensure that the hash key contains both their hashes.
        with:
          path: |
            /usr/share/miniconda/envs/graphein-dev/
          key: ${{ runner.os }}-env.${{ hashFiles('environment-dev.yml') }}

      - name: Build environment
        # if: steps.cache-environment.outputs.cache-hit != 'true'
        run: |
          conda env create -f environment-dev.yml

      - name: Run pytest
        run: |
          source activate graphein-dev
          pip install .
          pytest .

      - name: Upload code coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
      # No deps helps us check that all dependencies
      # are explicitly stated in environment.yml
      # - name: Run tests
      #   run: |
      #     source activate graphein-dev
      #     python -m pip install . --no-deps
      #     pytest .
